const data =
{
    "Philippines History": {
        "Enumaration": {
            "Bonifacio<br>Teodoro Plata<br>Valentin Diaz<br>Ladislao Diwa<br>Deodato Arellano": "FOUNDERS OF THE KATIPUNAN (July 7, 1892)",
            "1.Civic<br>2.Political<br>3.Moral": "Andres Bonifacio set three main objectives for the Katipunan:",
            "1. Maximo Inocencio.<br>2. Luis Aguad.<br>3. Victoriano Lucian.<br>4. Hugo Perez<br>5. Jose Llana<br>6. Antonio San Agustin<br>7. Agapito Conchu<br>8. Feliciano Cabuco.<br>9. Maximo Gregorio.<br>10. Eugenio Cabezas.<br>11. Severino Lapidario<br>12. Alfonso de Ocampo<br>13. Francisco Osorio": "Thirteen Martyrs of Cavite:"
        },
        "Chapter 10": {
            "Andres Bonifacio": "He founded the Katipunan, a revolutionary society aimed at Filipino independence",
            "Kataastaasan Kagalanggalang na Katipunan ng mga Anak ng Bayan": "KKK",
            "Civic": "Promote self-help and protect the weak and poor.",
            "Political": "Achieve Philippine independence from Spain.",
            "Moral": "Teach good manners, hygiene, and strong moral character.",
            "KKK": "A blood compact sealed their unity and patriotism.",
            "The first official flag ": "(by Benita Rodriguez & Gregoria de Jesus): red cloth with three white K's.",
            "Bonifacio's personal flag": "red cloth with a white sun (many rays) and three K's below it.",
            "Katungkulang Gagawin ng mga Anak ng Bayan": "Bonifacio created a moral guide for members called",
        },
        "Chapter 11": {
            "Andres Bonifacio": "Leader of the Katipunan.",
            "Emilio Jacinto": "Katipunan member and close aide of Bonifacio.",
            "Melchora Aquino (Tandang Sora)": "“Mother of the Katipunan”; provided shelter and support.",
            "Juan A. Ramos": "Son of Tandang Sora; the meeting was held in his yard.",
            "Francisco L. Roxas": "A Spaniard born in the Philippines who refused to support the Katipunan and threatened to report them.",
            "December 30, 1896, 7:03 AM": "When Jose Rizal was executed at Bagumbayan Field (Luneta).",
            "Luis Taviel de Andrade": "Rizal's Spanish military lawyer.",
            "Francisco Olive": "Conducted Rizal's preliminary investigation.",
            "Camilo Polavieja": "Governor General who signed the execution order.",
            "First Clash": "August 25, 1896",
            "Kataastaasang Sanggunian (Supreme Council)": "central government",
            "Sangguniang Bayan (Provincial Council)": "provincial level",
            "Sangguniang Balangay (Popular Council)": "municipal level",
            "Deodato Arellano (Supremo), Bonifacio (Comptroller), Plata, Diwa, Diaz": "First Council (1892):",
            "Roman Basa (Supremo), Bonifacio (Fiscal), Santiago, Molina": "Second Council (1893):",
            "Anak ng Bayan": "Katipon - Password",
            "Gom-Bur-Za": "Kawal - Password",
            "Rizal": "Bayani - Password",
            "Josefa Rizal - President<br>Gregoria de Jesus - Vice President<br>Marina Dizon - Secretary<br>Angelica Lopez Rizal - Fiscal":"Prominent women leaders included",
            "1. Magdiwang - favored the retention of the Katipunan<br>2. Magdalo - favored a change in theKatipunan structure.": "Two Factions of Katipunan",
            "Date: May 10, 1897<br>Place: Mount Tala, Maragondon, Cavite": "Execution of Andres Bonifacio",
        },
        "Chapter 12": {
            "Pact of Biak-na-Bato (1897)": "A truce between Filipino revolutionaries and the Spanish government. Allowed both sides to rest and recover.",
        },
        "Chapter 15": {
            "250,000 Filipinos ": "Estimated deaths on phil-american war"
        }
    },
    "Ped012": {
        "PE": {
            "It is an integral part of the educational program designed to promote the optimum development of the individual physically, socially, emotionally, and mentally through total body movement in the performance of properly selected physical activities (Andin, 1988).": "Physical Education",
            "VALUES- BENEFITS": "Physical<br>Social<br>Emotional<br>Mental<br>Spiritual",
            "fitness is defined as a set of abilities that an individual possesses in order to perform specific types of physical activity or to carry out daily tasks efficiently and effectively with alertness and vigor, without undue fatigue and still has an ample reserve energy to meet the other demands of daily life - recreational, sports, and other leisure activities, to handle life's emergency situations, to be healthy and to resist hypokinetic diseases (Corbin, Lindsey, & Welk, 2000).": "Physical Fitness",
            "Health-Related Fitness Components": "Cardiorespiratory Endurance<br>Muscular Strength<br>Muscular Endurance<br>Flexibility<br>Booy Composition",
            "Performance-Related Fitness Components": "Agility<br>Balance<br>Coordination<br>Reaction time<br>Power<br>Speed",
            "These are components of fitness that are important for health and performance of daily functional activities. Each health-related fitness component characteristic has a direct relationship to good health and reduced risk of hypokinetic disease.": "Health - Related Fitness (HRF)",
            "The ability of the heart, blood vessels, blood, and respiratory system to supply oxygen and fuel to the muscles at a steady rate for a considerable length of time. A fit person can persist in physical activity for relatively long periods without undue stress.": "Cardiorespiratory Endurance",
            "The ability of the muscle to exert maximum force against resistance. A fit person can do work or play that involves exerting force, such as lifting or controlling one's own body weight.": "Muscular Strength",
            "The ability of the muscles to repeatedly exert force against resistance or to sustain muscular contraction. A fit person can repeat movements for a long period without undue fatigue.": "Muscular Endurance",
            "The ability to move the body joints through a full range of motion (ROM) without discomfort or pain. It is affected by muscle length, joint structure and other factors, A fit person can move the body joints through a full range of motion in work and in play.": "Flexibility",
            "The relative percentage of muscle fat bone and other tissues that comprise the body. A fit person has relatively low, but not too low, percentage of body fat (body fatness). Body mass index (BMI) is a measurement tool that compares your height to your weight and gives you an indication of whether you are overweight, underweight or at a healthy weight for your height. Refer to Appendix A for the computation and qualitative description of BMI.": "Body Composition",
            "These are components of fitness that are important to athletic success and are not crucial for health. It is sometimes called skill-related fitness or sports/motor fitness because people who possess them find it easy to achieve high levels of performance in motor skills, such as those required in sports and specific types of jobs.": "Performance-Related Fitness (PRF)",
            "The ability to quickly and accurately change the direction of the movement of the entire body in space. Skiing and wrestling are examples of activities that require exceptional agility. Balance- The ability to maintain equilibrium while stationary or moving. Water skiing, performing on the balance beam, or working as a riveter on a high-rise building are activities that require exceptional balance.": "Agility",
            "The ability to combine the senses with the body parts to perform activities smoothly and accurately, Juggling, hitting a golf ball, batting a baseball, or kicking a ball are examples of activities requiring good coordination.": "Coordination",
            "The time elapsed between stimulation and the start of reaction to that stimulation. Driving a racing car and starting a sprint race require good reaction time.": "Reaction Time",
            "The ability to transfer energy into force at a fast rate. Throwing the discus and putting the shot are activities that require considerable power.": "Power",
            "The ability to perform a movement in a short period of time. A runner on track team or a wide receiver on a football team needs good foot and leg speed.": "Speed",
            "aids the circulatory system; fat loss; regulates appetite; increased flexibility; lowers blood pressure; lowers blood fats; strengthens muscles; stronger bones.": "1.	Physiological Benefits",
            "better sleep; relieves stress; relieves anxiety; gives renewed energy; keeps mind sharp.": "2.	Mental Health Benefits",
            "The type of exercise depends on the individual's fitness goal. The different types of exercise vary according to its needs and its effects. Some types of exercise improve flexibility and muscle strength. Others use the large muscles in the body to build heart strength. Still, others increase endurance. The three types of exercises fall into the following categories: aerobic, strength conditioning, and flexibility. 1This chapter also includes, as well, the necessary equipment for specific exercises. Exercise prescription commonly refers to the specific plan of fitness- related activities that are designed for a specified purpose. It is based on the individual's level of health and fitness, and his or her aims. Due to the specific and unique needs and interests of the individual, the goal of exercise prescription should be successful integration of exercise principles and behavioral techniques that motivates the participants to adhere, thus achieving their goals.": "EXERCISE PRESCRIPTION",
            "Types of Exercises ": "A.Aerobic Exercises<br>B.Strength and Endurance Conditioning Exercises<br>C. Flexibility and Mobility Exercises",
            "It refers to any physical activity that makes an individual sweat, causes one to breathe harder, and gets the heart beating faster than at rest. It strengthens the heart and lungs and trains the cardiovascular system to manage and deliver oxygen more quickly and efficiently throughout the body. Aerobic exercise uses the large muscle groups, is rhythmic in nature, and can be maintained continuously for at least 10minutes (Ricketts, 2009). Cardiovascular system-is made up of your heart, blood, and blood vessels e.g. arteries, veins, and capillaries that transport blood throughout the body Aerobic-refers to how your body uses oxygen to sufficiently meet energy demands during exercise.": "Aerobic Exercises",
            "The most popular and simplest way to determine the target heart rate, based on VO2max and their correlation with heart rate.": "Karvonen Method ",
            "Functional fitness exercises train the muscles to work together and prepare them for daily tasks by simulating common movements one might do at home, at work or in sports. While using various muscles in the upper and lower body at the same time, functional fitness exercises also emphasize core stability, It is about training your body to handle real-life situations.": "Strength and Endurance Conditioning Exercises",
            "The muscles are made to contract and relax to gain tones. The muscles change length by either shortening or lengthening.": "1. Isotonic Exercise ",
            "The muscles undergo tension and hold certain position for some time in order to develop muscle strength, The muscle remains in the same length.": "2. Isometric Exercise",
            "The muscles contract at constant speed that is done with machine velocity, Stack weights control the performer to move faster.": "3. Isokinetic Exercise",
            "As the term flexibility refers to the total available range of motion around a joint, however, flexibility does not necessarily translate to moving well. Mobility expresses how well a person can move through the appropriate functional range of motion for a joint within a given movement pattern. To get the most out of training for life and sport, flexibility and mobility training part should be part of any workout program. In order to perform exercises or physical activities pain and injury-free, one needs to have the appropriate level of flexibility and mobility to go through the full range of motion. Types of Flexibility Exercises": "Flexibility and Mobility Exercises",
            "Types of Flexibility Exercises": "Yoga<br>Pilates",
            "It comes from the Sanskrit word Yuj meaning to yoke, join, or unite, This implies joining or integrating all aspects of the individual - body with mind and mind with soul - to achieve a happy, balanced and useful life, and spiritually, uniting the individual with the Supreme Being (Taylor, 2010).": "Yoga",
            "This method is called Contrology (from control and Greek oyia), The Pilates method seeks to increase the strength, flexibility, and control of the body, It is a body conditioning routine that helps to not only build flexibility, but also strength, endurance, and coordination (Roberts, 2002).": "Pilates",
            "This lesson deals with the different equipment needed in the different types of exercises to assist in the development of fitness levels and attaining the desired fitness goals. Aerobic Equipment Treadmills - This equipment can be used for walking or running in one place. It is a good choice to begin a new exercise routine because walking is well-tolerated by most individuals regardless of fitness levels and for most back conditions.": "Exercise Equipment",
            "This stationary machine mimics the action of stair climbing, walking or running without the risk of causing excessive pressure to the joints.": "Elliptical trainer",
            "This looks like a bicycle but without true wheels. This provides a low-impact and effective cardiovascular exercise without less stress on joints.": "Exercise or stationary bicycle",
            "These are not just for sailing and S&M. They are a must-have tool for anyone looking to pack on lean mass, The key to their effectiveness is that they work each arm independently, eliminating strength imbalances as they sculpt your muscle, says John Brookfield, creator of the original battling-ropes system. They also provide a killer cardio workout.": "Strength or Resistance Training Equipment Ropes",
            "These are used primarily for improving strength and balance.": "Resistance bands",
            "Some exercises are performed using a barbell (i.e, a straight metal bar) and weight plates that are placed on both ends, These exercises are very good at exercising stabilizing muscles on top of the main muscle groups, Since a person is not t stabilized in the same way it would be if using special gym exercises, stabilizing muscles are required to perform the exercises, This feature is helpful in making sure little muscles are not left behind and are allowed to keep up with bigger ones.": "Barbell",
            "A weighted medicine ball can provide an endless variety of core strength workouts like the seated oblique twist. Medicine balls come in a variety of sizes, weights, and textures and can be used alone or with a partner to fully work the core and upper body. To avoid serious injury while using a medicine ball, it is a good idea to get instructions from a book, video, or a personal trainer before one start tossing these monsters around.": "Medicine Balls",
            "The main benefit to using dumbbell exercises in your workout, routines is that on top of exercising the main muscles, dumbbell exercises will also require the input from various stabilizing muscles as well. This is in contrast to exercising on gym-type machines where main targeted muscles are isolated and are the only ones being utilized. Dumbbell exercises allow complicit muscles to grow in strength together and prevent muscle groups from developing independently and out of sync.": "Dumbbells",
            "These do not only enable a person to stretch out the different parts of the body but also enable one to improve balance.": "Flexibility and Mobility Equipment Exercise balls",
            "This is used in increasing your muscles' range of motion.": "Stretching straps",
            "This is stimulating the nervous system in such a way that the brain frees the your muscle's tone, loosening the guitar string. Self-myofascial release, has transformed from a once mysterious technique used only by professional athletes, coaches, and therapists to a familiar everyday practice for people at all levels of fitness, Self-myofascial release is a fancy term for self-massage to release muscle tightness or trigger points.": "Foam rolling",
            "This is handy to have if a person regularly does floor-based strength training moves, they are also great to have if one regularly takes Pilates or yoga classes.": "Exercise Mat",
            "This is basically just a wide and flexible band that requires strength to stretch any further than about shoulder width apart. The band should have a handle or something on the end that one can put the foot into. This way, an exerciser can attach it to the ankle and stretch it out using the leg, this will work the hip muscle if stretching out side to side. The band can also be used to stretch forward with the leg or to extend the leg backward.": "Stretch Band",
            "This highly-durable self-myofascial release (SMR) is an easy way to activate trigger points in muscles and relax much stressed areas.": "Rubber lacrosse ball",
            "Phases of Exercises": "Warm-up<br>Conditioning<br>Cool-down",
            "up phase of exercise prepares the body for the activity of the conditioning part of a workout. Warming up before exercise allows the body to adjust gradually to the increased demand on the heart, muscles, one's breathing, and circulation. Warm-ups also increase the body's temperature slowly, improve flexibility, and protect against injury and muscle soreness. Warm-ups involve light aerobic activities, such as walking slowly for 5 to 10 minutes or a moderate version of the conditioning exercise and should be based on a person's physical characteristics and conditioning activity. For strength training, the warm-up is done by moving the joints and muscles.": "Warm-up",
            "the exercises are performed that produce fitness benefits, such as calorie-burning, endurance-building, or muscle-strengthening. A person may choose an aerobic exercise, such as swimming, or the elliptical jogger, or one may lift free weights, perform circuit training on weight machines or play a high-intensity sport such as soccer or basketball.": "Conditioning",
            "phase ends the exercise session with recovery time for the body. Cooling down requires one to keep moving after ending the conditioning phase. Cool- down movements should allow the heart rate, blood pressure, and body temperature to return slowly to normal. A gradual decrease in physical activity, such as slow walking, is a good way to cool down, A few stretching movements can also be performed to cool down.": "Cool-down",
            "Principles of Fitness Training ": "1. Overload<br>2. Specificity<br>3. Individuality<br>4. Recovery<br>5. Reversibility",
            "Refers to the observation that a body system must be exercised at a level beyond which it is presently accustomed. A specific body system gradually adapts to this overload until it reaches a state where adaptation is no longer observed. By and large, training consists of systematically exposing selected physiological systems to intensities of work that exceed those to which the system is already adapted.": "1. Overload",
            "The principle states that benefits associated with the training stimulus can only be achieved when it duplicates the movements and energy systems involved in the exercise, in other words, training effects are highly specific to the particular physiological systems overloaded, to the particular muscles used, and more specifically to the particular muscle fibers recruited to perform the work.": "2. Specificity",
            "The principle states that no two individuals are exactly alike. All individuals have different performances, fitness attributes, lifestyles, nutritional preferences, and they respond to exercise and its physical and social environments in their own unique way, it is essential that the exercise program caters to these individual needs and preferences.": "3.	Individuality",
            "It refers to the amount of time the body should be allowed to rest and recover from fatigue before the next activity begins. For instance, explosive type activities which last for 10-15 seconds (such as 100-meter track races) will require at least 2-3 minutes to completely restore the utilized ATP energy source in the muscle.": "4.	Recovery",
            "Fitness improvements are lost when demands on the body are lowered. If one stops exercising, up to 50% of fitness improvements are lost within 2months. Thus, the principle simply states that if an individual stops to exercise, the body returns to its initial level of fitness.": "5.	Reversibility"
        }
    },
    "Art app Final": {
        "Lesson 5": {
            "He stated that 'Art when really understood is the province of every human being'": "Robert Henri",
            "Are packed with numerus artifacts and interesting objects from all over the world that have survived centuries": "Museum",
            "A skilled worker who creates handmade items with both skill and artistic design, like jewelry, pottery, or decorative objects.": "Artisan",
            "were a type of social fellowship, prevalent during the middle ages, particularly the 13th century to 15th century, where towns had formalized groups of artisans or craftsmen who took on a particular specialization or trade: shoemakers, textile and glass workers, carpenters, carvers, masons armorers.": "Guilds",
            "A skilled worker who focuses more on practical and functional items, like furniture or tools.": "Craftsmen",
            "A person who draws detailed plans or technical drawings for buildings, machines, or other projects.": "Draftsman",
            "A person who designs buildings and oversees how they are built.": "Architect",
            "A person who uses science and math to design and build things like bridges, machines, or electrical systems.": "Engineer",
            "A person who actually constructs or puts together buildings and structures.": "Builder",
            "are all roles that were often combined into one person or group during the Middle Ages.": "draftsman<br> architect<br> engineer<br> builder",
            "There were those whose work station were segmented into two": "studiolo and the bottega",
            "Their beautiful vision and creative endeavors have to be recognized and appreciated to help build a career and open up opportunities. The artwork needs to be valued and receive serious consideration by galleries, exhibitions, biennials, and collectors alike.": "Artist",
            "are essentially the supporters and promoters of an artist's work. Their primary role is to spot talent, nurture an artist's career, generate exposure and establish his/her reputation.": "Dealer",
            "have an eye and passion for all art forms. They use their extensive knowledge of the subject and organizational skills to coordinate exhibitions at museums, galleries or public spaces. Curators are responsible for the conceptual development, design, layout and the execution of an art show. Art curators also research artists and write catalogue essays.": "Curator",
            "They analyze, evaluate and interpret the aesthetic value and significance of artwork that is displayed at galleries, museum exhibitions, private or public showings. Critics also comment and pass judgement on the technical factors, theme and artistic expression of the art being reviewed.": "Art critics",
            "They are an integral part of the art market that are keeping it afloat. The contributions of art collectors are vital for the very existence of artists, dealers, galleries and auction houses. Prominent collectors are very influent and can create recognition of an unknown artist by purchasing his work.": "Collectors",
            "Players in the World of Art": "Artist<br>Dealer<br>Curator<br>Art Critics<br>Collectors",
            "PRODUCTION PROCESS": "(1) preproduction<br>(2) production<br>(3) postproduction.",
            "The stage where the artist develops and explores their idea, which may take time or come quickly through research and experimentation.": "PREPRODUCTION",
            "The stage where the artist creates the artwork, using various materials and techniques, and where the idea starts to take physical form.": "PRODUCTION",
            "once an artwork is complete, decisions are made about how it will be shared with the public, often through museums, galleries, or performance spaces. The artist hopes the audience will connect with the unique message embedded in the work.": "POSTPRODUCTION",
            "is the mode of expression in which the concept, idea, or message is conveyed. It may be physical, such as paintings, sculptures, monuments, and structures; or it may even be ephemeral or transient, such as a track (sound recording), a film, or a performance.": "MEDIUM ",
            "shows the level of familiarity with the medium being manipulated, it suggests the necessity of additional tools or implements, or consideration of time, and specificity of the site of creation.": "Technique",
            "evolved over time, especially in how exhibitions are organized and presented.": "ENGAGEMENT WITH ART",
            "serve as a bridge between art and the public, making art relevant and accessible to contemporary audiences.": "Exhibitions",
            " are also a good way to introduce the artwork and opens it up for appreciation, critique, and analysis": "Publications",
            "The highest national recognition given to Filipino artists who have made notable contributions to Philippine arts.": "The Order of National Artists ( Tagad ng Sining)",
            " a painter and the very first recipient of this award who was touted as the 'Grand Old Man of Philippine Art' He was the sole awardee in the year 1972, a National Artist for Visual Arts": "Fernando Amorsolo",
            "established in 1992, celebrates artists who excel in traditional Filipino arts, such as weaving, pottery, and music. The award supports the preservation and teaching of these traditional skills.": "The National Living Treasures Award (Gawad sa Manlilikha ng Bayan)",
            "THE THREE OUTSTANDING ARTISTS IN MUSIC AND POETRY (1993)": "1. Ginaw Bilog<br>2. Masino Intaray<br>3. Samaon Sulaiman"
        },

        "Lesson 7": {
            "Is a term used to describe a period of history when stone were used to make tools for survival": "Stone Age",
            "Is a term image of men and women dressed in skin, huddling before a fire in a cave": "Conjures",
            "The later years of the old stone age": "PALEOLITHIC",
            "Middle stone age": "MESOLITHIC",
            "New stone age": "NEOLITHIC",
            "Three periods of stone age": "PALEOLITHIC <br> MESOLITHIC <br> NEOLITHIC",
            "is the earliest form of art, created by early humans in caves during the Ice Age as they sought shelter and warmth, leading them to make drawings and carvings on cave walls.": "Paleolithic Art",
            "is art from the Middle Stone Age, showing daily life and hunting scenes as people began to settle and adapt to their surroundings.": "Mesolithic Art",
            "is art from the New Stone Age, showing more advanced designs like pottery, weaving, and large stone structures, as people began farming and living in permanent homes.": "Neolithic Art",
            "Prehistoric Arts": "Paleolithic Art<br>Mesolithic Art<br>Neolithic Art",
            "Three period of egyptian civilization": "old <br> Middle <br> New Kingdom",
            " It was a palette that utilized and applied dark colors around King Narmer’s eyes.": "NARMER PALETTE",
            "is an ancient tomb built during Egypt's Old Kingdom to serve as the resting place for a pharaoh and is one of the world's great architectural wonders.": "The Great Pyramid Of Giza",
            "was an Egyptian queen known for her famous bust, which shows realistic and graceful features, highlighting the natural beauty often used in royal art.": "Queen Nefertiti",
            "was a young Egyptian pharaoh whose tomb, found in 1922, amazed the world with its gold treasures and famous gold mask.": "King Tutankhamen"
        },

        "Lesson 8": {
            "stands out among that other ancient culture for its development of naturalistic but idealized depictions of the human body, in which largely nude male figures were generally the focus of innovation.": "Ancient Greece art",
            "FOUR PERIODS OF GREEK ARTS": "Archaic Period<br>Classical Art<br>Hellenistic Period<br>Geometric Period",
            "the period between the decline of the Roman Empire and the Renaissance. It was a period that is characterized by ignorance and darkness. The printing press came later after the Middle Ages, so copies of the scriptures were done by hand. ": "MIDDLE AGES",
            "Roman art was influenced by Greece and can in part be taken as a descendant of ancient Greek painting and sculpture, but was also strongly influenced by the more local Etruscan art of Italy.": "ANCIENT ROME",
            "a general term for the art of the barbarian peoples who moved into formerly Roman territories. Celtic art in the 7th and 8th centuries saw a fusion with Germanic traditions through contact with the Anglo-Saxons creating what is called the Hiberno-Saxon style or Insular art, which was to be highly influential on the rest of the Middle Ages.": "EARLY MEDIEVAL ART/MIGRATION PERIOD ART",
            "crowning achievement were the monumental frescos and mosaics inside domed churches, most of which have not survived due to natural disasters and the appropriation of churches to mosques. ": "BYZANTINE ART",
            "focus on the arts of Ancient Greece and Rome, which led to many changes in both the technical aspects of painting and sculpture, as well as to their subject matter. ": "RENAISSANCE ART",
            "is vigorous and direct, was originally brightly colored, and is often very sophisticated. ": "ROMANESQUE ART",
            "a reaction against the idealist perfection of Classicism, employed distortion of light and spatial frameworks in order to emphasize the emotional content of a painting and the emotions of the painter.": "MANNERISM",
            "took the representationalism of the Renaissance to new heights, emphasizing detail, movement, lighting, and drama in their search for beauty. Was characterized by strongly religious and political themes; common characteristics included rich colors with a strong light and dark contrast.": "Baroque art",
            "was characterized by lighter, often jocular themes; common characteristics included pale, creamy colors, florid decorations and a penchant for bucolic landscapes. ": "ROCOCO ART",
            "was the artistic component of the intellectual movement known as the Enlightenment; the Enlightenment was idealistic, and put it in emphasis on objectivity, reason and empirical truth.": "NEOCLASSICISM",
            "The emphasis on the goodness of mankind. Most works also promoted justice, equality and social order. Artists also emphasized emotions and feelings of man, which was a deviation from the humanist principles of rationalism.": "ROMANTICISM",
            "focuses on the accuracy of details that depicts and somehow mirrors reality. Realism as a modern movement in art veered away from traditional forms of art.": "REALISM",
            "The movement started in France, which led to a break from the tradition in European painting.it is a style of painting that emerged in the mid-to late 1800s.": "IMPRESSIONISM",
            "It is an art movement that emerged in France, which is a result of both the influence and rejection of Impressionism. Most artists that belong to this movement started off as impressionists but later on saw the inherent limitations and flaws of impressionism.": "POST-IMPRESSIONISM",
            "As an art movement, it is considered as a response to empirical realism of impressionism. Most painters who subscribe to such movement rely on a systematic and scientific techniques that have a predetermined visual effects not only on the art work itself but also how the audience perceive the art.": "NEW-IMPRESSIONISM",
            "Between 1890 and 1910, countries from Europe and the United States witnessed the emergence and flourishing of a new art style. This ornamental style of art was a break from the Conservative historicism, which was the prevailing and dominant theme of most Western artworks.": "ART NOUVEAU",
            "This is a style of painting that emerged in France around the turn of the twentieth century. What makes it revolutionary is that they used pure and vibrant colors by applying straight from the paint tubes directly to the canvas.": "FAUVISM",
            "This style would later on have a huge influence on artists during the twentieth century. highlighted the two dimensional surface of the picture plane. Focusing on a flat surface was a rejection of the dominant techniques like the use of perspective, foreshortening, and modeling.": "CUBISM",
            "It is an early twentieth century art movement that started in Italy, which highlighted the speed, energy, dynamism and power of machines.": "FUTURISM"
        },

        "Lesson 9": {
            "Is an art movement from the 1980s that revived the style of Pop Art, especially inspired by Andy Warhol and his peers. It mixed popular culture with the use of ready-made objects, similar to the earlier Dada movement. Neo-Pop artworks often looked like photos because of their clean, precise style, but without showing the artist’s personal touch.": "Neo-Pop Art",
            "Is a type of modern art where the artist transforms a space using various objects, materials, lights, sounds, or even scents, creating an immersive experience for viewers. It is often large-scale, site-specific, and sometimes temporary.": "Installation Art",
            "Is a style of art where the artist creates very detailed and realistic images, often based on photographs, making the artwork look almost like a real photo.": "Photorealism",
            "Is a type of art where artists shape or change natural landscapes using materials like rocks, soil, or plants, creating large outdoor works that blend with nature.": "Earth Art",
            "Is a form of public art that includes murals, stencils, stickers, and installations, often made in urban spaces using different styles and materials. It grew from graffiti and is meant to be seen by everyone in public places.": "Street Art"
        },
        "Lesson 10": {
            "refers to the distinctive handling of elements and media associated with the work of an individual artist, a school, a movement, or a specific culture or time period (Fichner-Rathus, 2013).": "Style",
            "is what the audience sees a finished product put harmoniously (or not) according to the different principles of design. In essence, form is the totality of the artwork, which includes the textures, colors, and shapes utilized by the artist.": "Form",
            "of an artwork includes not only its form but also its subject matter and underlying meanings or themes (Fichner-Rathus, 2013).": "Content",
            "can be defined as doing something without prior preparation. Within the present context, improvisation has become an integral part of the arts.": "Improvisation"
        }

        

    }
}
